import { Story, Page } from '../types';

export const MOCK_STORIES: Story[] = [
  {
    id: 'mock-001',
    title_km: 'ទន្សាយនិងអណ្តើក',
    title_en: 'The Hare and the Tortoise',
    title_fr: 'Le Lièvre et la Tortue',
    level: 'L1',
    dev_stage: '1-2',
    is_free: true,
    cover_image_url: 'https://picsum.photos/seed/hare/400/300',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-002',
    title_km: 'ក្របីនិងក្អែក',
    title_en: 'The Buffalo and the Crow',
    title_fr: 'Le Buffle et le Corbeau',
    level: 'L2',
    dev_stage: '2-3',
    is_free: true,
    cover_image_url: 'https://picsum.photos/seed/buffalo/400/300',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-003',
    title_km: 'ព្រះច័ន្ទនិងទន្សាយ',
    title_en: 'The Moon and the Rabbit',
    title_fr: 'La Lune et le Lapin',
    level: 'L3',
    dev_stage: '2-3',
    is_free: false,
    cover_image_url: 'https://picsum.photos/seed/moon/400/300',
    created_at: new Date().toISOString(),
  },
];

export const MOCK_PAGES: Record<string, Page[]> = {
  'mock-001': [
    {
      id: 'p1-1',
      story_id: 'mock-001',
      page_number: 1,
      text_km: 'នៅក្នុងព្រៃមួយ មានទន្សាយមួយ និងអណ្តើកមួយ។',
      text_en: 'In a forest, there lived a hare and a tortoise.',
      text_fr: 'Dans une forêt, vivaient un lièvre et une tortue.',
      illustration_url: 'https://picsum.photos/seed/p1a/800/600',
      audio_url_km: null,
      audio_url_en: null,
      audio_url_fr: null,
    },
    {
      id: 'p1-2',
      story_id: 'mock-001',
      page_number: 2,
      text_km: 'ទន្សាយនិយាយថា "ខ្ញុំលឿនជាងអ្នកណាក្នុងព្រៃ!"',
      text_en: 'The hare said, "I am the fastest in the forest!"',
      text_fr: 'Le lièvre dit : « Je suis le plus rapide de la forêt ! »',
      illustration_url: 'https://picsum.photos/seed/p1b/800/600',
      audio_url_km: null,
      audio_url_en: null,
      audio_url_fr: null,
    },
    {
      id: 'p1-3',
      story_id: 'mock-001',
      page_number: 3,
      text_km: 'អណ្តើកឆ្លើយថា "តោះប្រណាំង!"',
      text_en: 'The tortoise replied, "Then let us race!"',
      text_fr: 'La tortue répondit : « Alors faisons la course ! »',
      illustration_url: 'https://picsum.photos/seed/p1c/800/600',
      audio_url_km: null,
      audio_url_en: null,
      audio_url_fr: null,
    },
  ],
  'mock-002': [
    {
      id: 'p2-1',
      story_id: 'mock-002',
      page_number: 1,
      text_km: 'ក្របីធំមួយចេញទៅស្រែ ហើយក្អែកមួយហើរលើខ្នងវា។',
      text_en: 'A great buffalo went to the fields, with a crow riding on its back.',
      text_fr: 'Un grand buffle allait aux champs, un corbeau perché sur son dos.',
      illustration_url: 'https://picsum.photos/seed/p2a/800/600',
      audio_url_km: null,
      audio_url_en: null,
      audio_url_fr: null,
    },
  ],
  'mock-003': [
    {
      id: 'p3-1',
      story_id: 'mock-003',
      page_number: 1,
      text_km: 'ព្រះច័ន្ទភ្លឺ ហើយទន្សាយតូចមួយក្រឡេកមើលវា។',
      text_en: 'The moon shone bright, and a little rabbit looked up at it.',
      text_fr: 'La lune brillait, et un petit lapin la regardait.',
      illustration_url: 'https://picsum.photos/seed/p3a/800/600',
      audio_url_km: null,
      audio_url_en: null,
      audio_url_fr: null,
    },
  ],
};
